trigger:
  - main

pool:
  name: Self-hosted # Ensure this matches your self-hosted agent's pool name

variables:
  DOTNET_CLI_HOME: $(System.DefaultWorkingDirectory) 
  
steps:
  # Step 0: Set HOME environment variable
  - script: |
      export HOME=$(System.DefaultWorkingDirectory)
      echo "HOME is set to $HOME"
    displayName: 'Set HOME environment variable'

  # Step 1: Install the .NET SDK
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  # Step 2: Restore Dependencies for the Library Project
  - script: dotnet restore "VivekK_301311622_COMP367_Lab4/VivekK_301311622_COMP367_Lab4.csproj"
    displayName: 'Restore NuGet Packages for Library Project'

  # Step 3: Build the Library Project
  - script: dotnet build "VivekK_301311622_COMP367_Lab4/VivekK_301311622_COMP367_Lab4.csproj" --configuration Release
    displayName: 'Build Library Project'

  # Step 4: Pack the Library Project as a NuGet Package
  - script: dotnet pack "VivekK_301311622_COMP367_Lab4/VivekK_301311622_COMP367_Lab4.csproj" --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack Library Project as NuGet Package'

  # Step 5: Restore Dependencies for the Console Project
  - script: dotnet restore "Lab4Console/Lab4Console.csproj"
    displayName: 'Restore NuGet Packages for Console Project'

  # Step 6: Build the Console Project
  - script: dotnet build "Lab4Console/Lab4Console.csproj" --configuration Release
    displayName: 'Build Console Project'

  # Step 7: Pack the Console Project as a NuGet Package
  - script: dotnet pack "Lab4Console/Lab4Console.csproj" --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack Console Project as NuGet Package'

  # Step 8: Authenticate with Azure Artifacts Feed
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with NuGet'

  # Step 9: Push the Library NuGet Package to Azure Artifacts
  - script: dotnet nuget push "$(Build.ArtifactStagingDirectory)/VivekK_301311622_COMP367_Lab4.*.nupkg" --source https://pkgs.dev.azure.com/Vivekkundaliya/VivekK_301311622_COMP367_Lab4/_packaging/Lab4feed/nuget/v3/index.json --api-key AzureArtifacts --skip-duplicate
    displayName: 'Push Library NuGet Package to Azure Artifacts'

  # Step 10: Push the Console NuGet Package to Azure Artifacts
  - script: dotnet nuget push "$(Build.ArtifactStagingDirectory)/Lab4Console.*.nupkg" --source https://pkgs.dev.azure.com/Vivekkundaliya/VivekK_301311622_COMP367_Lab4/_packaging/Lab4feed/nuget/v3/index.json --api-key AzureArtifacts --skip-duplicate
    displayName: 'Push Console NuGet Package to Azure Artifacts'
